EXP:
  MODEL_NAME: "pprfcn"
  EXP_ID: "pprfcn_default"

DATALOADER:
  datapath: "data/c_0.9_c_0.1.json"
  load_img: True
  crop: False
  norm_data: True
  data_aug_shift: True
  data_aug_color: True

TRAIN:
  num_epochs: 200
  l2: 0.0

MODEL:
  PPRFCN:
    backbone: "resnet18"
