EXP:
  MODEL_NAME: "vtranse"
  EXP_ID: "vtranse_default"

DATALOADER:
  datapath: "data/c_0.9_c_0.1.json"
  load_img: True
  crop: False
  norm_data: True
  data_aug_shift: True
  data_aug_color: True

TRAIN:
  num_epochs: 200
  l2: 1e-4

MODEL:
  VTRANSE:
    feature_dim: 512
    visual_feature_size: 3
    # same as feature dim in the Supplementary material, Table 4
    predicate_embedding_dim: 2048
    backbone: 'resnet18'

